version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:latest
    container_name: postgres-container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: challengedb

  load_data_service:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/code

    depends_on:
      - db

    command: python load_data.py

volumes:
  postgres_data:
